# SwiftLint Configuration for dogetionary
# Generated to enforce code quality and prevent common issues

# Paths to exclude from linting
excluded:
  - Pods
  - .build
  - DerivedData
  - .swiftpm

# Opt-in rules (not enabled by default)
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments for tracking work
  - line_length # Will configure separately
  - trailing_whitespace # Auto-formatted by Xcode

# Rule configurations

# Critical safety rules
force_unwrapping:
  severity: error # Prevent force unwraps (!)

force_try:
  severity: error # Prevent force try (try!)

force_cast:
  severity: error # Prevent force casts (as!)

# Prevent print statements in production code
no_print:
  severity: error

# File and function length
file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 40
  error: 80

type_body_length:
  warning: 300
  error: 500

# Line length
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

# Nesting depth
nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

# Identifier naming
type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID
    - URL
    - UUID

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k
    - to
    - db
    - vm
    - at
    - on
    - in
    - of

# Prevent large files
large_tuple:
  warning: 3
  error: 4

# Function parameters
function_parameter_count:
  warning: 6
  error: 8

# Custom rules
custom_rules:
  # Prevent unsafe array subscripting
  array_subscript_safety:
    name: "Array Subscript Safety"
    regex: '\[[0-9]+\](?!\s*=)'
    message: "Direct array subscripting can crash. Use .first, .last, or check bounds"
    severity: warning

  # Prefer Logger over print
  logger_over_print:
    name: "Use Logger instead of print"
    regex: '^\s*print\('
    message: "Use os.log Logger instead of print statements"
    severity: error

  # Prevent TODO without context
  todo_with_context:
    name: "TODO with Context"
    regex: '//\s*TODO:?\s*$'
    message: "TODO should include description of what needs to be done"
    severity: warning

  # Prefer Logger.error for errors
  logger_for_errors:
    name: "Use Logger for Error Handling"
    regex: '(catch\s*\{[^}]*print|catch\s*let\s+\w+\s*\{[^}]*print)'
    message: "Use Logger.error() in catch blocks instead of print"
    severity: warning

  # Encourage weak self in closures
  weak_self_in_closures:
    name: "Weak Self in Closures"
    regex: '\{\s*\[(?!weak\s+self)'
    message: "Consider using [weak self] to prevent retain cycles"
    severity: warning
    excluded: ".*Test\\.swift"

# Analyzer rules (requires building)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Reporter (output format)
reporter: "xcode" # or "json", "html", "emoji"
